export const experiences = [
  {
    date: " September 2024 - June 2025",
    title: "Associate Software Engineer",
    subtitle: "CIMET Sales Pvt. Ltd.",
    order:1,
    description: " Developed end-to-end vertical journey, improved site reliability by resolving key issues and reducing code duplication, enhanced CMS configurability with modular components, built responsive UIs using TypeScript and React, developed robust APIs with PostgreSQL, and boosted performance by removing heavy libraries.",
    tags: ["NextJS", "NodeJs", "Remix", "GraphQL", "Prisma ORM", "Keystone", "Elastic Search", "ShadCn", "Docker", "PostgreSQL"],
    site: "https://www.cimet.com.au/",
  },
  {
    date: "February - June 2024",
    title: "Web Developer Trainee",
    subtitle: "Requin Solutions",
    order:2,
    description: "Contributed to 4+ client (student) projects including Learning Management System, Result Management System, and job automation systems. Also maintained company website.",
    tags: ["Vue.Js", "React", "MongoDB", "Node", "Express", "Tailwind CSS", "Pug"],
    site: "https://www.requingroup.com/",
  },
  {
    date: "July - August 2023",
    title: "MERN Stack Intern",
    subtitle: "STPI",
    order:3,
    description: "Built a meeting booking system with client-admin flow, using APIs, sockets, and async logic",
    tags: ["React.JS", "TypeScript", "Express.Js","Node.Js","MongoDB", "Styled Components"],
    site: "http://stpi.in/",
  },
  {
    date: "June - August 2023",
    title: "React Developer",
    subtitle: "Blue Space Pvt. Ltd.",
    order:4,
    description: "Developed a community website for Cancer Patients- CAN, worked on the frontend.",
    tags: ["Figma", "React.Js", "Javascript", "Redux", "SASS", "SCSS"],
    site: "https://bluespace.in.net/",
  },
];
